version: "2"
services:
  jenkins:
    container_name: "he14vis-jenkins"
    build: ./jenkins/
    image: "he14vis/jenkins:2.46.2"
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
     - /mnt/data/jenkins:/var/jenkins_home
    ports:
     - 8081:8080
  registry:
    container_name: "he14vis-registry"
    restart: always
    image: "registry:2.6.1"
    ports:
     - 5000:5000
    #environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /mnt/data/registry/data:/var/lib/registry
      - /mnt/data/registry/certs:/certs
      - /mnt/data/registry/auth:/auth
